In [ ]:
#import

import pandas as pd
import numpy as np

#iris = pd.read_csv("gnb_normalize_dataset_fix.csv")
iris = pd.read_csv("iris.csv")
#iris = pd.read_csv("dataset_enzim_3_pca.csv")
#iris = pd.read_csv("dataset_enzim_selected_feature.csv")


iris.head()

#  variabel bebas
x = iris.drop(["variety"], axis = 1)
x.head()

#variabel tidak bebas
y = iris["variety"]
y.head()

# classification 
# please install scikit library 
# pip install -U scikit-learn

# separate the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 3)
#import from library 
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

# Call Gaussian Naive Bayes 
iris_model = GaussianNB()




# Insert the training dataset to  Naive Bayes function
NB_train = iris_model.fit(x_train, y_train)

# Next step: Prediction the x_test to the model built and save to the             y_pred variable 
# show the result of prediction 
y_pred = NB_train.predict(x_test)
np.array(y_pred) 

# show the y_test based on separation dataset
np.array(y_test)

# show the confusion matrix based on the prediction result 
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


#evaluate performance from the confusion matrix 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

# this value will show all probability for each predicted class 
NB_train.predict_proba(x_test)







              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       0.91      1.00      0.95        10
   Virginica       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


array([[1.00000000e+000, 3.97657460e-018, 1.81451748e-027],
       [1.00000000e+000, 2.45767206e-017, 1.05156114e-026],
       [1.00000000e+000, 3.89583737e-014, 3.68358197e-023],
       [1.00000000e+000, 5.28897442e-016, 1.92033111e-025],
       [1.00000000e+000, 1.51422161e-016, 1.84217680e-024],
       [1.80457208e-290, 1.40779591e-012, 1.00000000e+000],
       [1.40739455e-065, 9.99964106e-001, 3.58942386e-005],
       [1.00000000e+000, 1.92996899e-017, 1.36149579e-026],
       [2.19346281e-163, 2.46452157e-003, 9.97535478e-001],
       [3.07550445e-088, 9.82019881e-001, 1.79801191e-002],
       [2.66637859e-068, 9.99842060e-001, 1.57939971e-004],
       [1.00000000e+000, 3.87137953e-018, 1.20990548e-027],
       [2.23425927e-062, 9.99976684e-001, 2.33156717e-005],
       [6.40135244e-066, 9.99975094e-001, 2.49063452e-005],
       [4.62895800e-208, 1.53487073e-008, 9.99999985e-001],
       [1.00000000e+000, 1.03584907e-017, 7.09356512e-027],
       [1.12554698e-112, 9.32036282e-001